import Head from 'next/head'
import Banner from '@/components/home/Banner'
import Attributes from '@/components/home/Attributes'
import Uses from '@/components/home/Uses'
import Products from '@/components/home/Products'
import Plans from '@/components/home/Plans'
import JoinUs from '@/components/home/JoinUs'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel='stylesheet' href='css/main.css' />
      </Head>
      <Banner />
      <Attributes />
      <Uses />
      <Products />
      <Plans />
      <JoinUs />
    </>
  )
}
